name: Mangala Samaraweera
favicon: null
layout_spectrum: 0.8884846135042608
typography_spectrum: 0.2884187903255224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2113245229702443
  lightness: 0.16038299584761262
  saturation: 0.5269490350037813
  rhythmicContrast: 0.8989233509637415
purpose: []
